- hosts: all
  become: yes
  tasks:
    - name: Install repo key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
        state: present
    - name: Add the Jenkins repository
      apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
        state: present
    - name: Install Java
      apt:
        name: default-jre
        state: present
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes
    - name: Start and enable the Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
    - name: Install required packages
      apt:
        name: [
            git,
            phpunit
        ]
        state: present